SELECT A.CAR_ID, A.CAR_TYPE, 
    ROUND((A.DAILY_FEE * 30) * ((100 - C.DISCOUNT_RATE) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE 
WHERE 
    (A.CAR_TYPE = 'SUV' OR A.CAR_TYPE = '세단') 
    AND C.DURATION_TYPE = '30일 이상'
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
        WHERE B.CAR_ID = A.CAR_ID
        AND B.START_DATE <= '2022-11-30' 
        AND B.END_DATE >= '2022-11-01'
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;
