SELECT 
    ID, 
    CASE
        WHEN RN / CNT * 100.0 > 75 THEN 'LOW'
        WHEN RN / CNT * 100.0 > 50 THEN 'MEDIUM'
        WHEN RN / CNT * 100.0 > 25 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM (
    SELECT 
        ID,
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN,
        COUNT(*) OVER () AS CNT
    FROM ECOLI_DATA
) AS T
ORDER BY 1;