SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT INFO.USER_ID) AS USERS
FROM USER_INFO AS INFO
JOIN ONLINE_SALE AS SALE ON INFO.USER_ID = SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;