SELECT 
YEAR(B.SALES_DATE),
MONTH(B.SALES_DATE),
COUNT(DISTINCT(A.USER_ID)) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT(A.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%') , 1) AS PUCHASED_RATIIO

FROM USER_INFO AS A
JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID

WHERE A.JOINED LIKE '2021%'

GROUP BY 1, 2
ORDER BY 1, 2;