WITH RECURSIVE CTS AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, A.PARENT_ID, CTS.GENERATION + 1 AS GENERATION
    FROM CTS INNER JOIN ECOLI_DATA AS A ON CTS.ID = A.PARENT_ID 
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM CTS
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM CTS
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY 2;