SELECT ID, 'LOW' AS SIZE
FROM ECOLI_DATA
WHERE SIZE_OF_COLONY <= 100

UNION

SELECT ID, 'MEDIUM' AS SIZE
FROM ECOLI_DATA
WHERE SIZE_OF_COLONY BETWEEN 101 AND 1000

UNION

SELECT ID, 'HIGH' AS SIZE
FROM ECOLI_DATA
WHERE SIZE_OF_COLONY > 1000

ORDER BY 1;