SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(AMOUNT) * A.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
JOIN FOOD_ORDER AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE YEAR(B.PRODUCE_DATE) = 2022 AND MONTH(B.PRODUCE_DATE) = 5
GROUP BY 1
ORDER BY 3 DESC, 1 ASC;