SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A
JOIN (SELECT * FROM SKILLCODES WHERE CATEGORY = 'Front End') AS B
  ON B.CODE & A.SKILL_CODE != 0

GROUP BY 1, 2, 3, 4
ORDER BY 1;
