WITH CTE AS (
    SELECT 
        MEMBER_ID,
        RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) RK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M 
JOIN REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
JOIN CTE AS C ON R.MEMBER_ID = C.MEMBER_ID
WHERE RK = 1
ORDER BY 3, 2;