SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
WHERE (B.FISH_NAME, A.LENGTH) IN (
    SELECT D.FISH_NAME, MAX(C.LENGTH)
    FROM FISH_INFO AS C
    JOIN FISH_NAME_INFO AS D ON C.FISH_TYPE = D.FISH_TYPE
    GROUP BY 1
)
ORDER BY 1;
