WITH SKILL AS (
    SELECT
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONTEND,
        SUM(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END) AS PYTHON,
        SUM(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END) AS CSHARP
    FROM SKILLCODES
)

SELECT *
FROM (
    SELECT 
        CASE
            WHEN (D.SKILL_CODE & S.FRONTEND) > 0 AND (D.SKILL_CODE & S.PYTHON) > 0 THEN 'A'
            WHEN (D.SKILL_CODE & S.CSHARP) > 0 THEN 'B'
            WHEN (D.SKILL_CODE & S.FRONTEND) > 0 THEN 'C'
        END AS GRADE,
        D.ID,
        D.EMAIL
    FROM DEVELOPERS D
    CROSS JOIN SKILL S
) T
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;